SELECT * FROM EMPLOYEE;

SELECT EMPLOYEE_ID, EMPLOYEE_ADDRESS, EMPLOYEE_SALARY, EMP_JOIN_DATE
FROM EMPLOYEE;

SELECT DISTINCT EMPLOYEE_ADDRESS, EMPLOYEE_GENDER  
FROM EMPLOYEE;

SELECT * FROM EMPLOYEE
WHERE EMPLOYEE_ADDRESS = 'Japan'
AND EMPLOYEE_SALARY > 52000;

SELECT * FROM DEPT_MANAGER;

SELECT * FROM SALARY;

SELECT * FROM TITLES;

SELECT * FROM EMPLOYEE
WHERE EMPLOYEE_ADDRESS = 'Japan'
OR EMPLOYEE_ADDRESS = 'India'
OR EMPLOYEE_ADDRESS = 'Canada';

SELECT * FROM EMPLOYEE
WHERE EMPLOYEE_ADDRESS IN ('Tokyo','India','Canada');

SELECT * FROM EMPLOYEE
WHERE EMPLOYEE_SALARY BETWEEN 50000 AND 70000;

SELECT * FROM EMPLOYEE
WHERE EMPLOYEE_NAME LIKE '%S%'
ORDER BY EMPLOYEE_SALARY DESC;







