select * from EMPLOYEE;

select EMPLOYEE_ID, EMPLOYEE_NAME, EMPLOYEE_SALARY
from EMPLOYEE

create table VRUSHABH
(STUDENT_ID NUMERIC NOT NULL PRIMARY KEY,
STUDENT_NAME VARCHAR(50) NOT NULL,
STUDENT_EMAIL VARCHAR(200),
STUDENT_PHONE NUMERIC,
STUDENT_ADDRESS VARCHAR(500))

select * from VRUSHABH;